kind: Pod
apiVersion: v1
metadata:
 name: pod2
 labels: # any key and value pair
  author: Deepa
  type: webserver
  env: dev
spec:
 containers:
  - name: c1
    image: nginx
  - name: c2
    image: tomcat
  - name: c3
    image: ubuntu
    command: ["bash", "-c", "sleep 6000"]
